// Estado de los Catalogue 
export const GET_SUCCESSFUL_PRODUCTS = 'GET_SUCCESSFUL_PRODUCTS';
export const SELECT_VEHICLE_SUCCESS='SELECT_VEHICLE_SUCCESS';
export const SHOW_SUMMARY_SUCCESS ='SHOW_SUMMARY_SUCCESS';
export const SAVE_SUMMARY_SUCCESS ='SAVE_SUMMARY_SUCCESS';